---
- hosts: all

  tasks:

    - name: Dump Metadata
      delegate_to: localhost
      template:
        src: ./resources/metadata.md.j2
        dest: ./metadata.md

    - name: "Add SSH Authorization"
      authorized_key:
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        user: pi

    - name: "Set Hostname"
      become: yes
      hostname:
        name: "{{hostname}}"

    - name: "Update Packages"
      become: yes
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 259200
        autoremove: yes

    - name: "Install JDK"
      become: yes
      apt: 
        name: oracle-java8-jdk

- hosts: zookeepers

  vars:
    zookeeper_archive: zookeeper-{{ zookeeper_version }}.tar.gz
    zookeeper_home: ~/zookeeper-{{ zookeeper_version }}
    zookeeper_config: "{{ zookeeper_home }}/conf/zoo.cfg"
    zookeeper_data: "{{ zookeeper_home }}/var"

  tasks:

    - name: "Download & Unpack Zookeeper"
      unarchive:
        remote_src: yes
        src: "http://mirror.dsrg.utoronto.ca/apache/zookeeper/zookeeper-{{ zookeeper_version }}/{{ zookeeper_archive }}"
        dest: ~/
        creates: "{{ zookeeper_home }}/bin"

    - name: "Add Zookeeper Configuration"
      template:
        src: ./resources/zoo.cfg
        dest: "{{ zookeeper_home }}/conf"

    - name: "Set Zookeeper Configuration Hosts"
      with_items:
        - "{{ groups['zookeepers'] }}"
      lineinfile:
        path: "{{ zookeeper_config }}"
        line: server.{{ hostvars[item].zookeeper_id }}={{ item }}:2888:3888

    - name: "Create Zookeeper ID File"
      lineinfile:
        create: yes
        path: "{{ zookeeper_data }}/myid"
        line: "{{ zookeeper_id }}"

- hosts: brokers

  vars:
    kafka_archive: kafka_{{scala_version}}-{{kafka_version}}.tgz
    kafka_home: ~/kafka_{{scala_version}}-{{kafka_version}}
    kafka_config: "{{ kafka_home }}/config/server.properties"
    kafka_data: "{{ kafka_home }}/var"

  tasks:

    - name: "Download & Unpack Kafka"
      unarchive:
        remote_src: yes
        src: "http://mirror.dsrg.utoronto.ca/apache/kafka/{{kafka_version}}/{{kafka_archive}}"
        dest: ~/
        creates: ~/kafka_{{scala_version}}-{{kafka_version}}/bin

    - name: "Add Kafka Configuration"
      template:
        src: ./resources/server.properties
        dest: "{{ kafka_home }}/config"

    - name: "Add JVM Environment Variables"
      become: yes
      lineinfile:
        path: /etc/environment
        line: "{{ lookup('file', './resources/environment') }}"

    # - name:
    