---
- hosts: all

  vars:
    kafka_archive: kafka_{{scala_version}}-{{kafka_version}}.tgz
    kafka_home: ~/kafka_{{scala_version}}-{{kafka_version}}
    kafka_data: "{{ data_dir }}/kafka"
    log4j_config: "~/log4j.properties"

  tasks:

    - name: Dump Metadata
      delegate_to: localhost
      template:
        src: ./resources/metadata.md.j2
        dest: ./metadata.md

    - name: "Add SSH Authorization"
      authorized_key:
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        user: pi

    - name: "Set Hostname"
      become: yes
      hostname:
        name: "{{hostname}}"

    - name: "Update Packages"
      become: yes
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 259200
        autoremove: yes

    - name: "Install JDK"
      become: yes
      apt: 
        name: oracle-java8-jdk

    - name: "Download & Unpack Kafka"
      unarchive:
        remote_src: yes
        src: "http://mirror.dsrg.utoronto.ca/apache/kafka/{{kafka_version}}/{{kafka_archive}}"
        dest: ~/
        creates: ~/kafka_{{scala_version}}-{{kafka_version}}/bin

    - name: "Add log4j Configuration"
      template:
        src: ./resources/log4j.properties
        dest: "{{ log4j_config }}"

- hosts: zookeepers

  vars:
    kafka_home: ~/kafka_{{scala_version}}-{{kafka_version}}
    zookeeper_config: "~/zookeeper.properties"
    zookeeper_data: "{{ data_dir }}/zookeeper"

  tasks:

    - name: "Configure Zookeeper Service"
      become: true
      template:
        src: ./resources/zookeeper.service
        dest: /etc/systemd/system/zookeeper.service

    - name: "Add Zookeeper Configuration"
      template:
        src: ./resources/zookeeper.properties
        dest: "{{ zookeeper_config }}"

    - name: "Set Zookeeper Configuration Hosts"
      with_items:
        - "{{ groups['zookeepers'] }}"
      lineinfile:
        path: "{{ zookeeper_config }}"
        line: server.{{ hostvars[item].zookeeper_id }}={{ item }}:2888:3888

    - name: "Create Zookeeper ID File"
      lineinfile:
        create: yes
        path: "{{ zookeeper_data }}/myid"
        line: "{{ zookeeper_id }}"

- hosts: brokers

  vars:
    kafka_archive: kafka_{{scala_version}}-{{kafka_version}}.tgz
    kafka_home: ~/kafka_{{scala_version}}-{{kafka_version}}
    kafka_config: "~/server.properties"
    kafka_data: "{{ data_dir }}/kafka"

  tasks:

    - name: "Configure Kafka Service"
      become: true
      template:
        src: ./resources/kafka.service
        dest: /etc/systemd/system/kafka.service

    - name: "Add Kafka Configuration"
      template:
        src: ./resources/server.properties
        dest: "{{ kafka_config }}"

    - name: "Add JVM Environment Variables"
      become: yes
      template:
        src: ./resources/environment
        dest: /etc/environment
